[package]
name = "storage"
version.workspace = true
edition.workspace = true

[dependencies]
agent-core = { path = "../core" }
jieba-rs.workspace = true
rusqlite.workspace = true
serde_json.workspace = true
sha2.workspace = true
thiserror.workspace = true

[dev-dependencies]
rusqlite.workspace = true
